name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH for EC2 instance
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy project to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_INSTANCE_IP }} "
        sudo yum install -y git &&
        rm -rf /home/ec2-user/app &&
        mkdir -p /home/ec2-user/app &&  
        cd /home/ec2-user/app && 
        
        git clone https://github.com/ArchitectsGuild/api . "

    - name: Installing npm packages
      run: |
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 ec2-user@${{ secrets.EC2_INSTANCE_IP }} "
        curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash - &&
        sudo yum install -y nodejs &&
        sudo npm install -g aws-cdk" 

    - name: Deploy using CDK on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 ec2-user@${{ secrets.EC2_INSTANCE_IP }} "
        cd /home/ec2-user/app && 
        cdk synth && 
        cdk deploy --require-approval never"
