name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH for EC2 instance
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy project to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no ./ ec2-user@${{ secrets.EC2_INSTANCE_IP }}:/home/ec2-user/app

    - name: Deploy using CDK on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_INSTANCE_IP }} "
        cd /home/ec2-user/app && 
        npm install && 
        cdk bootstrap && 
        cdk deploy --require-approval never"
